[project]
name = "leetcode"
version = "0.1.0"
description = "Solving some leetcode to get the hang of programming after a while."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
]
